my_t = ()
print(my_t)
my_t=(1,2,3)
print(my_t)
my_t=(1,"hello",3.4)
print(my_t)
my_t=("mouse",[8,4,6],(1,2,3))
print(my_t)
my_t=('p','e','r','m','i','t')
print(my_t[0])
print(my_t[5])
n_t=("mouse",[8,4,6],(1,2,3))
print(n_t[0][3])
print(n_t[1][1])
print("Sliced:",my_t[1:4])
for letter in(my_t):
    print("hello",letter)
